[phases.setup]
nixPkgs = [
  "nodejs_18",
  "ghostscript",
  "mupdf"
]

[phases.install]
cmds = ["cd serviceUploader && npm ci --prefer-offline --no-audit"]

[start]
cmd = "cd serviceUploader && npm start"
